/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    trips: Trip;
    activities: Activity;
    countries: Country;
    accommodations: Accommodation;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    trips: TripsSelect<false> | TripsSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    accommodations: AccommodationsSelect<false> | AccommodationsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for accessibility and SEO (describe what's in the image)
   */
  alt: string;
  /**
   * Optional caption to display with the media
   */
  caption?: string | null;
  /**
   * Type of media content
   */
  mediaType?: ('photo' | 'video' | 'audio' | 'document') | null;
  /**
   * Categorize the media for better organization
   */
  category?:
    | (
        | 'landscape'
        | 'portrait'
        | 'food'
        | 'architecture'
        | 'culture'
        | 'activity'
        | 'accommodation'
        | 'transportation'
        | 'map'
        | 'document'
        | 'other'
      )
    | null;
  location?: {
    /**
     * Where this photo/video was taken
     *
     * @minItems 2
     * @maxItems 2
     */
    gps?: [number, number] | null;
    /**
     * Name of the place (e.g., "Issyk-Kul Lake, Kyrgyzstan")
     */
    locationName?: string | null;
    /**
     * Country where this media was captured
     */
    country?: (number | null) | Country;
  };
  /**
   * Trip this media is associated with
   */
  relatedTrip?: (number | null) | Trip;
  /**
   * Activities shown or related to this media
   */
  relatedActivities?: (number | Activity)[] | null;
  photographyInfo?: {
    /**
     * Camera model used
     */
    camera?: string | null;
    /**
     * Lens used for the photo
     */
    lens?: string | null;
    settings?: {
      aperture?: string | null;
      shutterSpeed?: string | null;
      iso?: number | null;
      focalLength?: number | null;
    };
  };
  usage?: {
    /**
     * Name of the photographer (if not you)
     */
    photographer?: string | null;
    licenseType?: ('own' | 'cc' | 'stock' | 'permission' | 'fair-use') | null;
    /**
     * Attribution text if required
     */
    attribution?: string | null;
  };
  seo?: {
    /**
     * Title for search engines (if different from alt text)
     */
    title?: string | null;
    /**
     * Keywords for better searchability
     */
    keywords?:
      | {
          keyword?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Mark as featured media for homepage or special collections
   */
  featured?: boolean | null;
  /**
   * Tags for organization and filtering (e.g., "sunset", "mountain", "street-food")
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: number;
  /**
   * Official country name
   */
  name: string;
  /**
   * ISO 3166-1 alpha-3 country code (e.g., USA, GBR, KGZ)
   */
  countryCode: string;
  /**
   * Official capital city name
   */
  capital: string;
  /**
   * ISO 4217 currency code (e.g., USD, EUR, KGS)
   */
  currency: string;
  /**
   * Full currency name (e.g., US Dollar, Euro, Kyrgyzstani Som)
   */
  currencyName?: string | null;
  /**
   * Approximate population count
   */
  population?: number | null;
  /**
   * List of official languages
   */
  officialLanguages?:
    | {
        language: string;
        id?: string | null;
      }[]
    | null;
  /**
   * List of time zones used in the country
   */
  timeZones?:
    | {
        /**
         * e.g., UTC+6, GMT+1
         */
        timezone: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Primary or most practiced religion in the country
   */
  mainReligion?:
    | ('christianity' | 'islam' | 'judaism' | 'hinduism' | 'buddhism' | 'sikhism' | 'secular' | 'mixed' | 'other')
    | null;
  /**
   * Percentage of population practicing the main religion
   */
  mainReligionPercentage?: number | null;
  /**
   * General visa requirements and travel information
   */
  visaRequirements?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * General safety assessment for travelers
   */
  safetyLevel?: ('very_safe' | 'safe' | 'moderate' | 'caution' | 'high_risk') | null;
  /**
   * Recommended months to visit with explanations
   */
  bestTimeToVisit?:
    | {
        month:
          | 'january'
          | 'february'
          | 'march'
          | 'april'
          | 'may'
          | 'june'
          | 'july'
          | 'august'
          | 'september'
          | 'october'
          | 'november'
          | 'december';
        /**
         * Why this month is good for visiting
         */
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Important emergency contact numbers
   */
  emergencyNumbers?: {
    police?: string | null;
    medical?: string | null;
    fire?: string | null;
    tourist?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trips".
 */
export interface Trip {
  id: number;
  title: string;
  status?: ('draft' | 'published') | null;
  coverImage: number | Media;
  /**
   * Select 3-10 key images that represent the best moments of this trip
   */
  highlightsMedia?:
    | {
        media: number | Media;
        /**
         * Brief description of why this is a trip highlight
         */
        caption?: string | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  country: number | Country;
  /**
   * Track which regions/provinces you visited within the country for better geographic organization
   */
  regionsVisited?:
    | {
        /**
         * e.g., "Issyk-Kul Region", "Naryn Province", "Chuy Oblast"
         */
        regionName: string;
        regionType?:
          | ('province' | 'region' | 'oblast' | 'state' | 'territory' | 'county' | 'district' | 'other')
          | null;
        /**
         * Key attractions, activities, or experiences in this region
         */
        highlights?: string | null;
        id?: string | null;
      }[]
    | null;
  period?: string | null;
  budget?: {
    amount?: number | null;
    currency?: string | null;
    perPerson?: boolean | null;
  };
  characteristics?: {
    /**
     * Select and rank the main activities that defined this trip
     */
    mainActivities?:
      | {
          activity: number | Activity;
          priority?: ('primary' | 'secondary' | 'notable') | null;
          /**
           * Approximate days dedicated to this activity
           */
          daysSpent?: number | null;
          personalRating?: ('1' | '2' | '3' | '4' | '5') | null;
          /**
           * Your experience, tips, or memorable moments with this activity
           */
          notes?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Select accommodations you want to highlight from this trip
     */
    featuredAccommodations?:
      | {
          accommodation: number | Accommodation;
          /**
           * How many nights you stayed here during this trip
           */
          nights?: number | null;
          /**
           * Your personal experience at this accommodation during this specific trip
           */
          tripNotes?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  itinerary?:
    | (
        | {
            time?: string | null;
            locationName: string;
            /**
             * @minItems 2
             * @maxItems 2
             */
            location?: [number, number] | null;
            /**
             * Which region/province this location is in (e.g., "Issyk-Kul Region", "Naryn Province")
             */
            regionProvince?: string | null;
            description?: string | null;
            activities?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            accommodation?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            transportation?: {
              arrivalMethod?:
                | (
                    | 'walking'
                    | 'rental_car'
                    | 'public_bus'
                    | 'taxi'
                    | 'train'
                    | 'flight'
                    | 'boat'
                    | 'bicycle'
                    | 'hitchhiking'
                    | 'tour_bus'
                    | 'other'
                  )
                | null;
              departureMethod?:
                | (
                    | 'walking'
                    | 'rental_car'
                    | 'public_bus'
                    | 'taxi'
                    | 'train'
                    | 'flight'
                    | 'boat'
                    | 'bicycle'
                    | 'hitchhiking'
                    | 'tour_bus'
                    | 'other'
                  )
                | null;
              travelTime?: {
                value?: number | null;
                unit?: ('minutes' | 'hours' | 'days') | null;
              };
              distance?: {
                value?: number | null;
                unit?: ('km' | 'mi') | null;
              };
              /**
               * Tips, costs, booking info, etc.
               */
              transportationNotes?: string | null;
            };
            accommodationDetails?: {
              accommodation?: (number | null) | Accommodation;
              /**
               * If not in the accommodations database
               */
              alternativeAccommodation?: string | null;
              checkIn?: string | null;
              checkOut?: string | null;
              /**
               * e.g., "Double room", "Dormitory bed", "Private yurt"
               */
              roomType?: string | null;
              /**
               * Your experience, what was included, pros/cons
               */
              accommodationNotes?: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
            };
            expenses?:
              | {
                  category:
                    | 'accommodation'
                    | 'food'
                    | 'transportation'
                    | 'activities'
                    | 'shopping'
                    | 'fuel'
                    | 'entrance_fees'
                    | 'tips'
                    | 'emergency'
                    | 'other';
                  description?: string | null;
                  amount?: number | null;
                  currency?: string | null;
                  /**
                   * If paid in local currency
                   */
                  exchangeRate?: number | null;
                  paymentMethod?: ('cash' | 'card' | 'mobile' | 'transfer') | null;
                  id?: string | null;
                }[]
              | null;
            gallery?:
              | {
                  media: number | Media;
                  caption?: string | null;
                  isHighlight?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'fullDay';
          }
        | {
            locationName: string;
            description?: string | null;
            /**
             * @minItems 2
             * @maxItems 2
             */
            location?: [number, number] | null;
            /**
             * Which region/province this waypoint is in (e.g., "Issyk-Kul Region", "Naryn Province")
             */
            regionProvince?: string | null;
            gallery?:
              | {
                  media: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'waypoint';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  /**
   * Select the type of activity or choose "Other" to specify a custom activity
   */
  activityType:
    | 'roadtrip'
    | 'citytrip'
    | 'backpacking'
    | 'cultural-tour'
    | 'hiking'
    | 'trekking'
    | 'mountain-climbing'
    | 'rock-climbing'
    | 'camping'
    | 'wildlife-safari'
    | 'diving'
    | 'snorkeling'
    | 'swimming'
    | 'kayaking'
    | 'rafting'
    | 'surfing'
    | 'fishing'
    | 'horseback-riding'
    | 'cave-exploring'
    | 'zip-lining'
    | 'paragliding'
    | 'skydiving'
    | 'bungee-jumping'
    | 'museum-visit'
    | 'historical-site'
    | 'local-market'
    | 'food-tour'
    | 'cooking-class'
    | 'language-exchange'
    | 'spa-wellness'
    | 'yoga-retreat'
    | 'beach-relaxation'
    | 'hot-springs'
    | 'public-transport'
    | 'car-rental'
    | 'flight'
    | 'border-crossing'
    | 'other';
  /**
   * Specify the custom activity name when "Other" is selected
   */
  customActivityName?: string | null;
  /**
   * Auto-generated from activity type or custom name, can be overridden
   */
  displayName?: string | null;
  /**
   * Categorize the activity for better organization
   */
  category?:
    | (
        | 'travel-transport'
        | 'outdoor-adventure'
        | 'water-sports'
        | 'cultural-educational'
        | 'relaxation-wellness'
        | 'extreme-sports'
        | 'food-dining'
        | 'shopping-markets'
        | 'nightlife-entertainment'
        | 'photography-sightseeing'
      )
    | null;
  difficulty?: ('easy' | 'moderate' | 'challenging' | 'expert' | 'na') | null;
  duration?: {
    value?: number | null;
    unit?: ('minutes' | 'hours' | 'days' | 'weeks') | null;
    /**
     * e.g., "Half day", "Full day", "Multi-day trek"
     */
    note?: string | null;
  };
  /**
   * Brief description of what this activity involves
   */
  description?: string | null;
  requirements?: {
    physicalFitness?: ('none' | 'basic' | 'good' | 'excellent') | null;
    equipment?:
      | {
          item?: string | null;
          essential?: boolean | null;
          id?: string | null;
        }[]
      | null;
    skills?: string | null;
    permits?: string | null;
  };
  costInfo?: {
    priceRange?: ('free' | 'budget' | 'moderate' | 'expensive' | 'luxury' | 'variable') | null;
    averageCost?: number | null;
    currency?: string | null;
    /**
     * Additional cost information, seasonal variations, etc.
     */
    costNotes?: string | null;
  };
  seasonality?: {
    bestMonths?: ('01' | '02' | '03' | '04' | '05' | '06' | '07' | '08' | '09' | '10' | '11' | '12')[] | null;
    weatherDependency?: ('none' | 'low' | 'medium' | 'high') | null;
    seasonalNotes?: string | null;
  };
  safety?: {
    riskLevel?: ('low' | 'moderate' | 'high' | 'extreme') | null;
    /**
     * Important safety considerations, warnings, precautions
     */
    safetyNotes?: string | null;
    emergencyInfo?: string | null;
  };
  /**
   * Tags for easier searching and filtering (e.g., "family-friendly", "solo-travel", "instagram-worthy")
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Activities that are commonly done together or as alternatives
   */
  relatedActivities?: (number | Activity)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accommodations".
 */
export interface Accommodation {
  id: number;
  /**
   * Full name of the accommodation
   */
  name: string;
  /**
   * Type of accommodation
   */
  type:
    | 'hotel'
    | 'hostel'
    | 'camping'
    | 'guesthouse'
    | 'resort'
    | 'apartment'
    | 'yurt'
    | 'wild_camping'
    | 'homestay'
    | 'ecolodge'
    | 'other';
  /**
   * Detailed description of the accommodation, amenities, and unique features
   */
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Brief summary for listings and previews
   */
  shortDescription?: string | null;
  /**
   * Exact location coordinates
   *
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number] | null;
  /**
   * Full address information
   */
  address: {
    street?: string | null;
    city: string;
    region?: string | null;
    postalCode?: string | null;
    /**
     * Select the country where this accommodation is located
     */
    country: number | Country;
  };
  contact?: {
    /**
     * Official website URL
     */
    website?: string | null;
    /**
     * Primary phone number with country code
     */
    phone?: string | null;
    /**
     * Contact email address
     */
    email?: string | null;
    /**
     * Links to book this accommodation on various platforms
     */
    bookingPlatforms?:
      | {
          platform: 'booking_com' | 'airbnb' | 'hotels_com' | 'expedia' | 'agoda' | 'hostelworld' | 'other';
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  pricing: {
    /**
     * General price category for this accommodation
     */
    priceRange: 'budget' | 'midrange' | 'luxury' | 'ultra_luxury';
    /**
     * Average price per night in EUR
     */
    averagePrice?: number | null;
    /**
     * Local currency code (e.g., EUR, USD, KGS)
     */
    currency?: string | null;
    /**
     * Information about price variations by season
     */
    seasonalPricing?: string | null;
  };
  quality?: {
    /**
     * Our star rating or equivalent
     */
    starRating?: ('1' | '2' | '3' | '4' | '5' | 'unrated') | null;
    cleanliness?: ('excellent' | 'very_good' | 'good' | 'fair' | 'poor') | null;
    service?: ('excellent' | 'very_good' | 'good' | 'fair' | 'poor') | null;
  };
  /**
   * Available amenities and services
   */
  amenities?:
    | {
        amenity?:
          | (
              | 'wifi'
              | 'parking'
              | 'restaurant'
              | 'bar'
              | 'pool'
              | 'spa'
              | 'gym'
              | 'laundry'
              | 'kitchen'
              | 'ac'
              | 'heating'
              | 'hot_water'
              | 'breakfast'
              | 'pet_friendly'
              | 'family_friendly'
              | 'accessible'
              | 'luggage_storage'
              | 'tour_desk'
              | 'other'
            )
          | null;
        /**
         * Additional details about this amenity
         */
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Types of travelers this accommodation is best suited for
   */
  suitableFor?:
    | {
        travelerType:
          | 'solo'
          | 'couples'
          | 'families'
          | 'groups'
          | 'backpackers'
          | 'business'
          | 'adventure'
          | 'digital_nomads';
        id?: string | null;
      }[]
    | null;
  personalNotes?: {
    /**
     * When you stayed at this accommodation
     */
    stayDate?: string | null;
    /**
     * Would you recommend this accommodation to others?
     */
    wouldRecommend?: boolean | null;
    /**
     * What you liked most about this place
     */
    highlights?: string | null;
    /**
     * Any issues or things to be aware of
     */
    drawbacks?: string | null;
    /**
     * Helpful tips for future guests
     */
    tips?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'trips';
        value: number | Trip;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'countries';
        value: number | Country;
      } | null)
    | ({
        relationTo: 'accommodations';
        value: number | Accommodation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  mediaType?: T;
  category?: T;
  location?:
    | T
    | {
        gps?: T;
        locationName?: T;
        country?: T;
      };
  relatedTrip?: T;
  relatedActivities?: T;
  photographyInfo?:
    | T
    | {
        camera?: T;
        lens?: T;
        settings?:
          | T
          | {
              aperture?: T;
              shutterSpeed?: T;
              iso?: T;
              focalLength?: T;
            };
      };
  usage?:
    | T
    | {
        photographer?: T;
        licenseType?: T;
        attribution?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        keywords?:
          | T
          | {
              keyword?: T;
              id?: T;
            };
      };
  featured?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trips_select".
 */
export interface TripsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  coverImage?: T;
  highlightsMedia?:
    | T
    | {
        media?: T;
        caption?: T;
        order?: T;
        id?: T;
      };
  description?: T;
  country?: T;
  regionsVisited?:
    | T
    | {
        regionName?: T;
        regionType?: T;
        highlights?: T;
        id?: T;
      };
  period?: T;
  budget?:
    | T
    | {
        amount?: T;
        currency?: T;
        perPerson?: T;
      };
  characteristics?:
    | T
    | {
        mainActivities?:
          | T
          | {
              activity?: T;
              priority?: T;
              daysSpent?: T;
              personalRating?: T;
              notes?: T;
              id?: T;
            };
        featuredAccommodations?:
          | T
          | {
              accommodation?: T;
              nights?: T;
              tripNotes?: T;
              id?: T;
            };
      };
  itinerary?:
    | T
    | {
        fullDay?:
          | T
          | {
              time?: T;
              locationName?: T;
              location?: T;
              regionProvince?: T;
              description?: T;
              activities?: T;
              accommodation?: T;
              transportation?:
                | T
                | {
                    arrivalMethod?: T;
                    departureMethod?: T;
                    travelTime?:
                      | T
                      | {
                          value?: T;
                          unit?: T;
                        };
                    distance?:
                      | T
                      | {
                          value?: T;
                          unit?: T;
                        };
                    transportationNotes?: T;
                  };
              accommodationDetails?:
                | T
                | {
                    accommodation?: T;
                    alternativeAccommodation?: T;
                    checkIn?: T;
                    checkOut?: T;
                    roomType?: T;
                    accommodationNotes?: T;
                  };
              expenses?:
                | T
                | {
                    category?: T;
                    description?: T;
                    amount?: T;
                    currency?: T;
                    exchangeRate?: T;
                    paymentMethod?: T;
                    id?: T;
                  };
              gallery?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    isHighlight?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        waypoint?:
          | T
          | {
              locationName?: T;
              description?: T;
              location?: T;
              regionProvince?: T;
              gallery?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  activityType?: T;
  customActivityName?: T;
  displayName?: T;
  category?: T;
  difficulty?: T;
  duration?:
    | T
    | {
        value?: T;
        unit?: T;
        note?: T;
      };
  description?: T;
  requirements?:
    | T
    | {
        physicalFitness?: T;
        equipment?:
          | T
          | {
              item?: T;
              essential?: T;
              id?: T;
            };
        skills?: T;
        permits?: T;
      };
  costInfo?:
    | T
    | {
        priceRange?: T;
        averageCost?: T;
        currency?: T;
        costNotes?: T;
      };
  seasonality?:
    | T
    | {
        bestMonths?: T;
        weatherDependency?: T;
        seasonalNotes?: T;
      };
  safety?:
    | T
    | {
        riskLevel?: T;
        safetyNotes?: T;
        emergencyInfo?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  relatedActivities?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  countryCode?: T;
  capital?: T;
  currency?: T;
  currencyName?: T;
  population?: T;
  officialLanguages?:
    | T
    | {
        language?: T;
        id?: T;
      };
  timeZones?:
    | T
    | {
        timezone?: T;
        id?: T;
      };
  mainReligion?: T;
  mainReligionPercentage?: T;
  visaRequirements?: T;
  safetyLevel?: T;
  bestTimeToVisit?:
    | T
    | {
        month?: T;
        reason?: T;
        id?: T;
      };
  emergencyNumbers?:
    | T
    | {
        police?: T;
        medical?: T;
        fire?: T;
        tourist?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accommodations_select".
 */
export interface AccommodationsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  description?: T;
  shortDescription?: T;
  location?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        region?: T;
        postalCode?: T;
        country?: T;
      };
  contact?:
    | T
    | {
        website?: T;
        phone?: T;
        email?: T;
        bookingPlatforms?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
      };
  pricing?:
    | T
    | {
        priceRange?: T;
        averagePrice?: T;
        currency?: T;
        seasonalPricing?: T;
      };
  quality?:
    | T
    | {
        starRating?: T;
        cleanliness?: T;
        service?: T;
      };
  amenities?:
    | T
    | {
        amenity?: T;
        notes?: T;
        id?: T;
      };
  suitableFor?:
    | T
    | {
        travelerType?: T;
        id?: T;
      };
  personalNotes?:
    | T
    | {
        stayDate?: T;
        wouldRecommend?: T;
        highlights?: T;
        drawbacks?: T;
        tips?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}