services:
  postgres:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: roamingroutes
      POSTGRES_USER: rruser
      POSTGRES_PASSWORD: z8ZWOUcPaXKgiAn0sATYNb7N61Lth0JyLbH
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rruser -d roamingroutes"]
      interval: 5s
      timeout: 5s
      retries: 5

  payload:
    image: node:20-alpine
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules  # anonymous volume to prevent overwriting
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: