services:
  postgres:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: roamingroads
      POSTGRES_USER: rruser
      POSTGRES_PASSWORD: z8ZWOUcPaXKgiAn0sATYNb7N61Lth0JyLbH
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rruser -d roamingroads"]
      interval: 5s
      timeout: 5s
      retries: 5

  payload:
    image: node:20-alpine
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules  # anonymous volume to prevent overwriting
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      # Ensure Payload connects to the local postgres service by service name
      - DATABASE_URI=postgresql://rruser:z8ZWOUcPaXKgiAn0sATYNb7N61Lth0JyLbH@postgres:5432/roamingroads
    env_file:
      - .env.local
    # Use a minimal entrypoint script so the dev server is PID 1 (reduces duplicate logs)
    entrypoint: ["/bin/sh", "-c", "./scripts/docker-entrypoint.sh"]
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:

# Note: Now uses local PostgreSQL database by default for safe development