services:
  payload:
    image: node:20-alpine
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules  # anonymous volume to prevent overwriting
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    # Allocate TTY + keep STDIN open so we can answer Payload's migration prompts
    stdin_open: true
    tty: true
    # Run install (first time), ensure import map is generated for richText, then start dev server
    command: sh -c "npm install && npx payload generate:importmap && npm run dev"
    restart: unless-stopped

# Note: No local database needed - using live Neon database via .env.local